# -*- coding: utf-8 -*-
"""sk_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10NVu233soBn5OqYU42Eubqdq8IjWvcyW
"""

import numpy as np
import scipy as sp
from matplotlib import pyplot as plt

def sk(signal, Fs, Nw, No, win_type):

  # signal    = Signal for SK
  # Fs        = Sampling frequency of signal
  # Nw        = ARRAY! Width/no. of points of window
  # No        = ARRAY! No. of overlap points
  # win_type  = STRING! Type of window i.e. hann

  for i in range(0, len(Nw)):
    
    n_points = Nw[i]
    n_over = No[i]

    sfreq, times, stft = sp.signal.stft(signal, fs=Fs, window=win_type, nperseg=n_points, noverlap=n_over, return_onesided=True)

    speckurt = np.zeros(len(stft))

    for j in range(0, len(sfreq)):

      speckurt[j] = (np.mean(np.abs(stft[j,:])**4) / np.mean(np.abs(stft[j,:])**2)**2) - 2

    plt.plot(sfreq, speckurt, label = "Window Len = {}".format(n_points))
  
  plt.title("Spectral Kurtosis")
  plt.xlabel("Frequency [Hz]")
  plt.ylabel("Amplitude")
  plt.legend(loc='best')

  return